name: load current planet position
on:
  workflow_dispatch:
  schedule:
    - cron: '1 */6 * * *'
jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: npm install
        run: |
          npm install
          npm run planet-position
          git add .
          git commit -m 'Update planet position'
          git push origin main
