name: load plant position
on:
  workflow_dispatch:
  schedule:
    - cron: '1 */6 * * *'
jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name : Setting up CI
        run: |
          git config user.name "GitHub CI"
          git config user.email "<>"
      - name : Updating json
        run: |
          npm i
          npm run planet-position
      - name : Committing changes
        run: |
          git add .
          git commit -m "CI : Updated plannet JSON" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs: [ load ]
    uses: Panneerselvamr/horoscope/.github/workflows/static.yml@main